[tool.commitizen]
name = "cz_conventional_commits"
version = "0.93.5"
tag_format = "v$version"
bump_message = "bump: release $current_version â†’ $new_version"
version_files = [
    "pyproject.toml:version",
    "andeboxlib/cli.py:__version__",
    "docs/conf.py:release"
]
update_changelog_on_bump = true
major_version_zero = true
